const Rules = [
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'},
    {action: "money", amount:1, color: 'green'},
    {action: "money", amount:2, color: 'green'},
    {action: "move", amount:7, color: 'yellow'},
    {action: "poison", color: 'brown'},
    {action: "doNothing", color: 'teal'},
    {action: "money", amount:1, color: 'green'},
    {action: "money", amount:2, color: 'green'},
    {action: "doNothing", color: 'teal'},
    {action: "move", amount:-5, color: 'yellow'},
    {action: "doNothing", color: 'teal'},
    {action: "move", amount:-7, color: 'yellow'},
    {action: "double", color: 'pink'},
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, // needs changing
    {action: "money", amount:1, color: 'green'},
    {action: "money", amount:2, color: 'green'},
    {action: "doNothing", color: 'teal'}, // needs changing
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, // needs changing
    {action: "doNothing", color: 'teal'}, // needs changing
    {action: "doNothing", color: 'teal'}, // needs changing
    {action: "doNothing", color: 'teal'}, // 24 Checkpoint square
    {action: "doNothing", color: 'teal'}, // ------------------------------------------------------------------------------------
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'},
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
    {action: "doNothing", color: 'teal'}, 
];

export default Rules;